name: CI/CD-CLOUD-practice2

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: "alirs2002"
          password: "@kdkobe4142"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cloud_practice2/Dockerfile
          push: true
          tags: your-dockerhub-username/your-image-name:latest

      - name: Logout from Docker Hub
        run: docker logout
